### ISSUE TITLE
Add support for batch operations

### ISSUE THREAD

**Issue by icorderi** [Seagate/kinetic-py#31]
## Proto 
Kinetic [proto] changes.

## Design
- New `begin_batch()` operation in the `Client` returning a `Batch` object.
- New `Batch` class:
```py
class Batch(Object):
    def put(*args, **kwargs): pass
    def delete(*args, **kwargs): pass
    # No other calls are allowed on the object after calling `commit`
    def commit(): pass
    # No other calls are allowed on the object after calling `abort`
    def abort(): pass 
```

## Example
```py
import kinetic 
c = kinetic.Client('10.1.2.3')
b = c.begin_batch()
b.put('foo','bar', version='0.1')
b.put('xyz', 'asd', force=True)
b.delete('some')
b.commit()
```

[proto]: https://github.com/Seagate/kinetic-protocol/blob/features/batch-operation/kinetic.proto

**Comment by pauldardeau** [comment]
First version of batch.py and test_batch.py checked in.

**Comment by icorderi** [comment]
@pauldardeau, it seems you are backing the methods inside `Batch` with new methods in the client. It would be best not to add any new methods on the clients surface other than `begin_batch`.

For instance `Batch.put()` can do the following internally:
```python
def put(*args, **kwargs):
    """ blabla """
    # ...do some checks..
    kwargs['batch_id'] = self._batch_id 
    self._client._process(operations.Put(), *args, **kwargs)
```

Obviously the `Put` class in `operations.py` needs to be made aware of the new `batch_id` argument. Same goes for `Delete`.

By the way, I rebased the feature branch with the latest in _develop_ and pushed the new proto (342e524cc4f8cee47469b76eb8586ce2d71ca87b).

**Comment by pauldardeau** [comment]
All functionality present and all unit tests pass.

**Comment by icorderi** [comment]
@pauldardeau the tests need to call `self.buildKey()` or `self.buildKey(n)` to generate keys the test manager is aware of and can clean up after each test. 
You can find some examples in the client [tests](https://github.com/Seagate/kinetic-py/blob/develop/test/test_client.py).

**Comment by icorderi** [comment]
@pauldardeau, there is another issue on how the batch operations are being generated.

This might read ok, but in reality `_buildMessage` is for building the different keyvalue operations:
```python
class StartBatch(BaseOperation):

    def _build(self):
        # this is wrong
        return _buildMessage(self.m, messages.Command.START_BATCH, '')
```

This is the correct way to generate a proto with no body:
```python
class StartBatch(BaseOperation):

    def _build(self):
        # this is correct
        self.m.header.messageType = messages.Command.START_BATCH
        return (self.m, None)
```

**Comment by pauldardeau** [comment]
Updated with suggested changes.
